TITLE = "Asteroids"

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
TARGET_FPS = 60

PLAYER_RADIUS = 20
PLAYER_ROTATION_SPEED = 0.2
PLAYER_MOVE_SPEED = 0.2

ASTEROID_MOVE_SPEED = 0.1
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
