# General
CAPTION = 'Asteroids'

# Player
PLAYER_RADIUS: int = 20
PLAYER_MOVE_SPEED: float = 0.2
PLAYER_ROTATION_SPEED: float = 0.2
PLAYER_RELOAD_SPEED: float = 500.0  # milliseconds
PLAYER_HP: int = 5
PLAYER_INVINCIBILITY_DURATION: float = 3000.0  # milliseconds

# Missile
MISSILE_RADIUS: int = 5
MISSILE_SPEED: float = 0.5

# Asteroids
ASTEROID_SPAWN_RATE: float = 1000.0  # milliseconds

ASTEROID_SMALL_RADIUS: int = 20
ASTEROID_SMALL_SPEED: float = 0.1
ASTEROID_SMALL_SCORE: int = 100

ASTEROID_MEDIUM_RADIUS: int = 40
ASTEROID_MEDIUM_SPEED: float = 0.05
ASTEROID_MEDIUM_SCORE: int = 50

ASTEROID_LARGE_RADIUS: int = 60
ASTEROID_LARGE_SPEED: float = 0.02
ASTEROID_LARGE_SCORE: int = 20

# Misc
OBJECT_LINE_WIDTH: int = 2
